# Generated by Django 3.0.1 on 2020-01-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added'], 'verbose_name_plural': 'replies'},
        ),
    ]
